# Generated by Django 5.1.2 on 2024-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igrica_naslov', models.CharField(max_length=100)),
                ('igrica_sadrzaj', models.TextField()),
                ('igrica_vrijeme_objave', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupac_ime', models.CharField(max_length=25)),
                ('kupac_prezime', models.CharField(max_length=50)),
                ('kupac_broj_mobitela', models.CharField(max_length=10)),
                ('kupac_igrice', models.ManyToManyField(to='main.igrica')),
            ],
        ),
    ]
