# Generated by Django 5.1.6 on 2025-02-09 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Igrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igrica_naslov", models.CharField(max_length=255)),
                ("igrica_sadrzaj", models.TextField()),
                (
                    "igrica_vrijeme_objave",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rating", models.FloatField(default=0)),
                ("review_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Kupac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kupac_ime", models.CharField(max_length=25)),
                ("kupac_prezime", models.CharField(max_length=50)),
                ("kupac_broj_mobitela", models.CharField(max_length=10)),
                ("kupac_igrice", models.ManyToManyField(to="main.igrica")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "igrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="main.igrica",
                    ),
                ),
            ],
        ),
    ]
