# Generated by Django 5.1.2 on 2024-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrica',
            name='igrica_vrijeme_objave',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
